/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;


import DAO.AlunoDAO;
import DAO.BibliotecarioDAO;
import DAO.Conexao;
import static Main.main.identificacao;
import com.placeholder.PlaceHolder;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author g_net
 */
public class telaLogin extends javax.swing.JFrame {

    /**
     * Creates new form telaLogin1
     */

    PlaceHolder holder;
    private Image imagem;
    public String tipo = null;
    
    
    
    public telaLogin() {
        setContentPane(new JLabel(new ImageIcon(getClass().getResource("/icons/livro3.jpg"))));
        setTitle("Tela de Login");
         initComponents();
        
     
     
        holder = new PlaceHolder(textoDoUsuario, "Digite o Nome");
        holder.setColorHolder(new Color(150,150,150));

        holder = new PlaceHolder(textoDoCadeado, "Digite a Senha");
        holder.setColorHolder(new Color(150,150,150));
  
      
    }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        textoDoUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botaoEntrar = new javax.swing.JButton();
        comboBox1 = new javax.swing.JComboBox<>();
        textoDoCadeado = new javax.swing.JPasswordField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(50, 50));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        kGradientPanel1.setkEndColor(new java.awt.Color(30, 83, 72));
        kGradientPanel1.setkGradientFocus(50);
        kGradientPanel1.setkStartColor(new java.awt.Color(15, 205, 189));

        kGradientPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        kGradientPanel5.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel5.setkGradientFocus(100);
        kGradientPanel5.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel5.setPreferredSize(new java.awt.Dimension(87, 87));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bloqueio.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        kGradientPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        kGradientPanel6.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel6.setkGradientFocus(100);
        kGradientPanel6.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel6.setPreferredSize(new java.awt.Dimension(87, 87));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/do-utilizador.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        textoDoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        textoDoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textoDoUsuarioFocusGained(evt);
            }
        });
        textoDoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDoUsuarioActionPerformed(evt);
            }
        });
        textoDoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoDoUsuarioKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Impact", 0, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");

        botaoEntrar.setBackground(new java.awt.Color(255, 255, 255));
        botaoEntrar.setText("Entrar");
        botaoEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoEntrarMouseExited(evt);
            }
        });
        botaoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarActionPerformed(evt);
            }
        });
        botaoEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                botaoEntrarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                botaoEntrarKeyTyped(evt);
            }
        });

        comboBox1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        comboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma opção", "Aluno", "Bibliotecaria" }));
        comboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBox1MouseClicked(evt);
            }
        });
        comboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox1ActionPerformed(evt);
            }
        });
        comboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboBox1KeyPressed(evt);
            }
        });

        textoDoCadeado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        textoDoCadeado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textoDoCadeadoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(kGradientPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textoDoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textoDoCadeado))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(96, 96, 96))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoDoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoDoCadeado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(botaoEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(562, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textoDoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textoDoUsuarioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDoUsuarioFocusGained

    private void comboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox1ActionPerformed

    private void botaoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarActionPerformed
        Connection con = Conexao.AbrirConexao();
        BibliotecarioDAO sql_bib = new BibliotecarioDAO(con);
        AlunoDAO sql_alu = new AlunoDAO(con);
        String login = textoDoUsuario.getText();
        String senha = textoDoCadeado.getText();
        String tipo = (String)comboBox1.getSelectedItem();
        if(login.equalsIgnoreCase("") || senha.equalsIgnoreCase("") || login.equalsIgnoreCase("Digite o Nome") || senha.equalsIgnoreCase("Digite a Senha")){
            JOptionPane.showMessageDialog(null, "Nenhum campo pode está Vazio","ERROR",JOptionPane.WARNING_MESSAGE);
            textoDoUsuario.setBackground(new Color(255,100,100));
            textoDoCadeado.setBackground(new Color(255,100,100));
            
        }else if(tipo.equalsIgnoreCase("Selecione uma opção")){
            JOptionPane.showMessageDialog(null, "Selecione um tipo de usuario","ERROR",JOptionPane.WARNING_MESSAGE);
            comboBox1.setBackground(new Color(255,100,100));
            
        }else if(tipo.equalsIgnoreCase("Aluno")){
            try {
                if(sql_alu.Logar(login, senha) == true){
                    identificacao = sql_alu.getAluno().getNome();
                    main.alunoLogado = sql_alu.getAluno();
                    main.bibLogado = null;
                    new TelaAluno().setVisible(true);
                    this.dispose();
                        
                 
                }else{
                    JOptionPane.showMessageDialog(null, "Usuario ou senha incorretos","ERROR",JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(telaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else if(tipo.equalsIgnoreCase("Bibliotecaria")){
            try {
                if(sql_bib.Logar(login, senha) == true){
                    identificacao = sql_bib.getBibliotecario().getNome();
                    main.bibLogado = sql_bib.getBibliotecario();
                    main.alunoLogado = null;
                    new TelaBibliotecario().setVisible(true);
                    this.dispose();
                        
                 
                }else{
                    JOptionPane.showMessageDialog(null, "Usuario ou senha incorretos","ERROR",JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(telaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
            
    }//GEN-LAST:event_botaoEntrarActionPerformed

    private void botaoEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEntrarMouseEntered
        botaoEntrar.setBackground(new Color(30,83,72));        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEntrarMouseEntered

    private void botaoEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoEntrarMouseExited
        botaoEntrar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_botaoEntrarMouseExited

    private void textoDoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoDoUsuarioKeyPressed
        textoDoUsuario.setBackground(Color.white);
        if(evt.getKeyCode() == evt.VK_ENTER){
            botaoEntrarActionPerformed(new java.awt.event.ActionEvent(evt, WIDTH, tipo));
        }
    }//GEN-LAST:event_textoDoUsuarioKeyPressed

    private void comboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBox1MouseClicked
     comboBox1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_comboBox1MouseClicked

    private void botaoEntrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEntrarKeyTyped

    private void botaoEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botaoEntrarKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            botaoEntrarActionPerformed(new java.awt.event.ActionEvent(evt, WIDTH, tipo));
        }
    }//GEN-LAST:event_botaoEntrarKeyPressed

    private void comboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboBox1KeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){

           botaoEntrarActionPerformed(new java.awt.event.ActionEvent(evt, WIDTH, tipo));
        }
    }//GEN-LAST:event_comboBox1KeyPressed

    private void textoDoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDoUsuarioActionPerformed

    private void textoDoCadeadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoDoCadeadoKeyPressed
        textoDoCadeado.setBackground(Color.white);
        if(evt.getKeyCode() == evt.VK_ENTER){
            botaoEntrarActionPerformed(new java.awt.event.ActionEvent(evt, WIDTH, tipo));
        }
    }//GEN-LAST:event_textoDoCadeadoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new telaLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrar;
    private javax.swing.JComboBox<String> comboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel6;
    private javax.swing.JPasswordField textoDoCadeado;
    private javax.swing.JTextField textoDoUsuario;
    // End of variables declaration//GEN-END:variables
}
